<?php
/**
 * JOQ design-system footer.
 *
 * Shared by index.php, templates/newSingle.php and templates/newCategory.php.
 * Renders the app banner, brand row, link chips, Kape banner, WhatsApp CTA
 * and bottom bar using the joq-footer__* classes from
 * assets/css/joq-design-system.css.
 *
 * Optional, set as a global before including — get_template_part() loads the
 * file in its own scope, so a plain local variable would not survive:
 *
 *   $GLOBALS['joq_footer_last_news'] = true;
 *
 * Renders the "Më të fundit" AJAX strip above the footer. Article and category
 * pages set it; the homepage does not. The fragment it loads
 * (/myAjax/last-four-news2.html) is generated by pages/last-four-news.php and
 * still carries the old markup, so it is left untouched here.
 */

global $joq_footer_last_news, $joq_footer_last_news_cat;

$joq_theme_uri = '/wp-content/themes/joq';

if ( ! isset( $joq_footer_last_news ) ) {
    $joq_footer_last_news = false;
}

/* A page that is about one category sets $joq_footer_last_news_cat to that
   term id; the strip is then rendered here from that category instead of
   loading /myAjax/last-four-news2.html, which is one site-wide fragment and
   would put other categories' stories on the page. */
$joq_footer_cat_posts = array();
if ( $joq_footer_last_news && ! empty( $joq_footer_last_news_cat ) ) {
    $joq_footer_cat_q = new WP_Query( array(
        'post_type'           => 'post',
        'post_status'         => 'publish',
        'cat'                 => (int) $joq_footer_last_news_cat,
        'posts_per_page'      => 4,
        'ignore_sticky_posts' => true,
        'no_found_rows'       => true,
    ) );
    $joq_footer_cat_posts = $joq_footer_cat_q->posts;
}
?>

<!-- Footer -->
<footer class="joq-footer">
    <div class="joq-footer__accent"></div>

    <?php if ( $joq_footer_last_news ) : ?>
        <!-- Last News -->
        <?php /* Kept inside .joq-footer on purpose: .footer-last-news-title is
           hard-coded color:#fff in newstyle.css, so above the footer it would
           render white-on-white against the light page background. */ ?>
        <div class="joq-footer__inner" style="padding-top: 40px;">
            <div class="footer-last-news pc-only">
                <div class="footer-last-news-title">
                    M&euml; t&euml; fundit
                </div>
                <?php if ( $joq_footer_cat_posts ) : ?>
                <div class="footer-last-news-articles">
                    <?php foreach ( $joq_footer_cat_posts as $joq_fp ) :
                      $joq_fp_img = fix_post_thumbnail( get_the_post_thumbnail_url( $joq_fp->ID, 'img2' ) );
                    ?>
                    <div class="article-wrapper" style="width: 25%;">
                        <a href="<?php echo get_permalink( $joq_fp->ID ); ?>">
                            <div class="article-image" style="padding-bottom: 75%;<?php if ( $joq_fp_img ) : ?> background-image: url(<?php echo esc_url( $joq_fp_img ); ?>);<?php endif; ?> background-size: cover; background-position: center; border-top-left-radius: 10px; border-top-right-radius: 10px;"></div>
                            <div class="article-title">
                                <?php echo get_the_title( $joq_fp->ID ); ?>
                            </div>
                        </a>
                    </div>
                    <?php endforeach; ?>
                </div>
                <?php else : ?>
                <div class="footer-last-news-articles"></div>
                <script type="text/javascript">
                    if ($( window ).width() > 600) {
                        $.get( "/myAjax/last-four-news2.html", function( data ) {
                          $( ".footer-last-news-articles" ).html( data );
                        });
                    }
                </script>
                <?php endif; ?>
            </div>
        </div>
        <!-- End Last News -->
    <?php endif; ?>

    <!-- App download banner -->
    <div class="joq-footer__app-banner">
        <div class="joq-footer__app-banner-inner">
            <div>
                <span class="joq-footer__app-badge">
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><polyline points="20 6 9 17 4 12"/></svg>
                    Falas
                </span>
                <div class="joq-footer__app-title">Shkarko aplikacionin JOQ Albania</div>
                <div class="joq-footer__app-sub">Lajmet m&euml; t&euml; fundit, direkt n&euml; telefonin t&euml;nd.</div>
            </div>

            <div class="joq-footer__app-buttons">
                <a href="https://apps.apple.com/al/app/joq-al/id1224913299" target="_blank" rel="noopener" class="joq-footer__app-btn">
                    <svg width="26" height="26" viewBox="0 0 24 24" fill="currentColor"><path d="M17.05 12.54c-.02-2.3 1.88-3.4 1.96-3.46-1.07-1.56-2.73-1.78-3.32-1.8-1.41-.14-2.76.83-3.48.83-.72 0-1.83-.81-3.01-.79-1.55.02-2.98.9-3.77 2.28-1.61 2.79-.41 6.92 1.15 9.18.76 1.11 1.67 2.35 2.86 2.31 1.15-.05 1.58-.74 2.97-.74s1.78.74 3 .72c1.24-.02 2.02-1.13 2.78-2.24.88-1.29 1.24-2.54 1.26-2.6-.03-.01-2.41-.93-2.44-3.69zM14.8 5.36c.63-.77 1.06-1.83.94-2.9-.91.04-2.02.61-2.67 1.37-.58.67-1.09 1.76-.95 2.79 1.02.08 2.05-.52 2.68-1.26z"/></svg>
                    <span>
                        <small>Shkarko n&euml;</small>
                        <strong>App Store</strong>
                    </span>
                    <svg class="joq-footer__app-arrow" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>
                </a>

                <a href="https://play.google.com/store/apps/details?id=com.joqAlbania.al" target="_blank" rel="noopener" class="joq-footer__app-btn">
                    <svg width="26" height="26" viewBox="0 0 24 24" fill="currentColor"><path d="M3.6 1.84a1.5 1.5 0 0 0-.35.98v18.36c0 .38.13.72.35.98l.06.06L13.9 12v-.12zM17.3 15.4l-3.4-3.4v-.12l3.4-3.4.08.05 4.03 2.29c1.15.65 1.15 1.72 0 2.38l-4.03 2.29zM17.38 15.45 13.9 12 3.6 22.16c.38.4 1 .45 1.71.05zM17.38 8.55 5.31 1.74c-.71-.4-1.33-.35-1.71.05L13.9 12z"/></svg>
                    <span>
                        <small>Shkarko n&euml;</small>
                        <strong>Google Play</strong>
                    </span>
                    <svg class="joq-footer__app-arrow" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>
                </a>
            </div>
        </div>
    </div>

    <div class="joq-footer__inner">

        <!-- Brand + socials -->
        <div class="joq-footer__brand-row">
            <div class="joq-footer__brand">
                <img class="joq-footer__logo" src="<?php echo $joq_theme_uri; ?>/assets/images/WhiteLogoJoq.svg" width="90" height="36" alt="JOQ Albania" />
                <p class="joq-footer__tagline">
                    Krijuar m&euml; 5 shkurt 2010, platforma m&euml; e madhe e lajmeve unike, arg&euml;tuese dhe sociale n&euml; hap&euml;sir&euml;n shqipfol&euml;se.
                </p>
            </div>

            <div class="joq-footer__socials">
                <a href="https://www.facebook.com/joqalbania/" target="_blank" rel="noopener" class="joq-footer__social joq-footer__social--fb" title="Facebook">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M24 12.07C24 5.4 18.63 0 12 0S0 5.4 0 12.07C0 18.1 4.39 23.1 10.13 24v-8.44H7.08v-3.49h3.05V9.41c0-3.02 1.79-4.69 4.53-4.69 1.31 0 2.68.24 2.68.24v2.97h-1.51c-1.49 0-1.96.93-1.96 1.89v2.25h3.33l-.53 3.49h-2.8V24C19.61 23.1 24 18.1 24 12.07"/></svg>
                </a>
                <a href="https://www.instagram.com/joqalbania/" target="_blank" rel="noopener" class="joq-footer__social joq-footer__social--ig" title="Instagram">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><line x1="17.5" y1="6.5" x2="17.5" y2="6.5"/></svg>
                </a>
                <a href="https://www.youtube.com/channel/UCVsMVFcGZgxXTl5A-usiIBQ/?sub_confirmation=1" target="_blank" rel="noopener" class="joq-footer__social joq-footer__social--yt" title="YouTube">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M23.5 6.2a3 3 0 0 0-2.1-2.1C19.5 3.6 12 3.6 12 3.6s-7.5 0-9.4.5A3 3 0 0 0 .5 6.2C0 8.1 0 12 0 12s0 3.9.5 5.8a3 3 0 0 0 2.1 2.1c1.9.5 9.4.5 9.4.5s7.5 0 9.4-.5a3 3 0 0 0 2.1-2.1c.5-1.9.5-5.8.5-5.8s0-3.9-.5-5.8M9.6 15.6V8.4l6.2 3.6z"/></svg>
                </a>
                <a href="https://twitter.com/JoqAlbania" target="_blank" rel="noopener" class="joq-footer__social joq-footer__social--x" title="X">
                    <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor"><path d="M18.9 1.2h3.7l-8.1 9.2L24 22.8h-7.4l-5.9-7.6-6.7 7.6H.3l8.6-9.9L0 1.2h7.6l5.3 7zm-1.3 19.4h2L6.5 3.3H4.3z"/></svg>
                </a>
                <?php /* TODO: TikTok — the old footer shipped this icon with href="#", so the
                   real profile URL is unknown. Uncomment and fill in to restore it.
                <a href="" target="_blank" rel="noopener" class="joq-footer__social joq-footer__social--tt" title="TikTok">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor"><path d="M16.6 5.82A4.28 4.28 0 0 1 15.54 3h-3.09v12.4a2.59 2.59 0 0 1-2.59 2.5 2.59 2.59 0 1 1 .77-5.06V9.69a5.67 5.67 0 0 0-.77-.05A5.67 5.67 0 1 0 15.54 15.3V9.01a7.35 7.35 0 0 0 4.3 1.38V7.3a4.28 4.28 0 0 1-3.24-1.48"/></svg>
                </a>
                */ ?>
            </div>
        </div>

        <!-- Link chips -->
        <div class="joq-footer__links">
            <div class="joq-footer__links-group">
                <span class="joq-footer__links-label">Kategorit&euml;</span>
                <div class="joq-footer__chips">
                    <a href="/kategori/lajme.html" class="joq-footer__chip">Lajme</a>
                    <a href="/kategori/vec-e-jona.html" class="joq-footer__chip">Ve&ccedil; e jona</a>
                    <a href="/kosova/index.html" class="joq-footer__chip">Kosova</a>
                    <a href="/maqedoni/index.html" class="joq-footer__chip">Maqedoni</a>
                    <a href="/kategori/sport.html" class="joq-footer__chip">Sport</a>
                    <a href="/kategori/bota.html" class="joq-footer__chip">Bota</a>
                    <a href="/kategori/teknologji.html" class="joq-footer__chip">Teknologji</a>
                    <a href="/kategori/argetim.html" class="joq-footer__chip">Arg&euml;tim</a>
                    <a href="/kategori/sondazhe.html" class="joq-footer__chip">Sondazhe</a>
                    <a href="/kategori/kuriozitete.html" class="joq-footer__chip">Kuriozitete</a>
                    <a href="/kategori/thashetheme.html" class="joq-footer__chip">Thashetheme</a>
                    <a href="/kategori/shendeti.html" class="joq-footer__chip">Sh&euml;ndeti</a>
                    <a href="/kategori/udhetime.html" class="joq-footer__chip">Udh&euml;time</a>
                    <a href="/kategori/si-te.html" class="joq-footer__chip">Si t&euml;...</a>
                </div>
            </div>

            <div class="joq-footer__links-group">
                <span class="joq-footer__links-label">Rreth nesh</span>
                <div class="joq-footer__chips">
                    <a href="/faqe/rreth-nesh.html" class="joq-footer__chip joq-footer__chip--ghost">Rreth Nesh</a>
                    <a href="/faqe/puno-me-ne.html" class="joq-footer__chip joq-footer__chip--ghost">Puno me ne!</a>
                    <a href="/faqe/reklamo.html" class="joq-footer__chip joq-footer__chip--ghost">Marketing</a>
                    <a href="/faqe/kontakto.html" class="joq-footer__chip joq-footer__chip--ghost">Kontakt</a>
                    <a href="/faqe/politika-e-privatesise.html" class="joq-footer__chip joq-footer__chip--ghost">Politika e privat&euml;sis&euml;</a>
                    <a href="/faqe/kushtet-e-perdorimit.html" class="joq-footer__chip joq-footer__chip--ghost">Kushtet e p&euml;rdorimit</a>
                    <a href="/english/index.html" class="joq-footer__chip joq-footer__chip--ghost">English</a>
                </div>
            </div>
        </div>

        <?php /* Kape banner — the design system ships .joq-kape and KapeLogoWhite.svg,
           but no Kape URL exists anywhere in the theme. Fill in the href and
           uncomment to enable.
        <a href="" target="_blank" rel="noopener" class="joq-kape" style="margin-top: 36px;">
            <span class="joq-kape__orb joq-kape__orb--1"></span>
            <span class="joq-kape__orb joq-kape__orb--2"></span>
            <span class="joq-kape__orb joq-kape__orb--3"></span>

            <span class="joq-kape__content">
                <span class="joq-kape__left">
                    <img class="joq-kape__logo" src="<?php echo $joq_theme_uri; ?>/assets/images/KapeLogoWhite.svg" width="120" height="36" alt="Kape" />
                    <span class="joq-kape__sub">Zbulo oferta dhe zbritje ekskluzive n&euml; Kape.al</span>
                </span>
                <span class="joq-kape__right">
                    <span class="joq-kape__cta">
                        Vizito
                        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="7" y1="17" x2="17" y2="7"/><polyline points="7 7 17 7 17 17"/></svg>
                    </span>
                </span>
            </span>
        </a>
        */ ?>

        <!-- Send material CTA -->
        <div class="joq-footer__cta">
            <span class="joq-footer__cta-glow"></span>
            <div class="joq-footer__cta-content">
                <span class="joq-footer__cta-icon">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51a12.8 12.8 0 0 0-.57-.01c-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.872.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 0 1-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 0 1-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884a9.82 9.82 0 0 1 6.988 2.896 9.82 9.82 0 0 1 2.893 6.994c-.003 5.45-4.437 9.886-9.885 9.886m8.413-18.297A11.8 11.8 0 0 0 12.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.9 11.9 0 0 0 5.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.82 11.82 0 0 0-3.48-8.413"/></svg>
                </span>
                <div class="joq-footer__cta-text">
                    <strong>Ke di&ccedil;ka p&euml;r t&euml; treguar?</strong>
                    <span>D&euml;rgo materialin t&euml;nd dhe e publikojm&euml; ne.</span>
                </div>
            </div>
            <a href="https://wa.me/+355699299998" target="_blank" rel="noopener" class="joq-footer__btn">
                D&euml;rgo materialin t&euml;nd
                <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="5" y1="12" x2="19" y2="12"/><polyline points="12 5 19 12 12 19"/></svg>
            </a>
        </div>

        <!-- Bottom bar -->
        <div class="joq-footer__bottom">
            <div class="joq-footer__copy">
                &copy; <?php echo date( 'Y' ); ?> JOQ Albania. T&euml; gjitha t&euml; drejtat e rezervuara.
            </div>
            <?php /* Developer credit — .joq-footer__credit exists in the design system but
               the theme names no developer, so nothing is asserted here. Fill in and
               uncomment if you want it.
            <div class="joq-footer__credit">
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>
                Zhvilluar nga <a href="" target="_blank" rel="noopener"></a>
            </div>
            */ ?>
        </div>

        <!-- Powered by -->
        <div class="joq-footer__powered">
            <span>Powered by</span>
            <img class="joq-footer__powered-logo"
                 src="<?php echo $joq_theme_uri; ?>/assets/images/LightFullLogo800x200.svg"
                 width="800" height="200" alt="Zulbera" loading="lazy" decoding="async" />
        </div>

    </div>
</footer>

<button type="button" class="joq-scroll-top" aria-label="Kthehu lart">
    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="19" x2="12" y2="5"/><polyline points="5 12 12 5 19 12"/></svg>
</button>
<!-- End Footer -->
